### ISSUE TITLE
sign in not effective and signing up with one gmail as many times as possible

### ISSUE THREAD

**Issue by cckole** [quintuslabs/GroceryStore#2]
###  Proposals

I logged out my account and wanted to log in with the same account later in the day but, got a message that I should sign up with the same gmail I used. I couldnt log in at all. I went ahead and signed up again with the same gmail and details I used the first time, and it entered. I double checked by logging out and loggin in again,and the same thing repeated itself. In short, the only way to get into the app is through sign up. The log in isn't effective.

### Expected behaviour
My expectation was to be able to sign in at anytime after signing up the first time. 

### Steps to reproduce
Launch the app 

- sign up
-  After yoo've been taking into the app, Log out and try to log in with the same details
- You will get a message to sign up with the same gmail you used the first time. 
- sign up with the gmail and other info and see the error.

**Comment by quintuslabs** [comment]
This is a template not an fully functional app.  I am not using any server for storing data. for server side programming u can contact us. or u can use your own server side programming according to your requirement. i am just storing your login info in local storage when u logout that that time u clear your login info. that's why u can able to login using same email multiple times.
